### ISSUE TITLE
Math uses foundry sterling typeface

### ISSUE THREAD

**Issue by jsmailes** [ssloxford/beamer-oxford#2]
Text in the math environment (for example, `$a^n + b^n = c^n$` uses the regular text typeface (in this case, Foundry Sterling) instead of the usual LaTeX math typeface. This is seen in the file `example.pdf`, a screenshot of which is shown below:

<img width="312" alt="image" src="https://user-images.githubusercontent.com/3045045/175349023-590dacf1-dbaa-46a6-8a44-3e827276f475.png">

**Comment by eddsalkield** [comment]
Resolved in fd4d8bc6a7c9ebcafbc48c921d54667bce68659a.
